# Generated by Django 4.2.7 on 2023-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sns_email", models.CharField(max_length=50)),
                ("sns_password", models.CharField(max_length=15)),
            ],
        ),
    ]
