# Generated by Django 4.2.7 on 2023-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("age", models.IntegerField()),
                ("dateTimeOfPosting", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["dateTimeOfPosting"],
            },
        ),
    ]
